server.servlet.context-path=/myplanet

##Connection to database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/my_planet
spring.datasource.username=postgres
spring.datasource.password=1234
# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show.sql= true
# spring.datasource.dbcp2.test-while-idle= true
# spring.datasource.dbcp2.validation-query=select 1
